import { describe, expect, it } from 'vitest'
import { genId, readableSize } from '../common'
import { createConversation } from '../conversation'

describe('utils', () => {
  it('genId', () => {
    const id1 = genId()
    const id2 = genId()
    expect(id1).toBeTypeOf('string')
    expect(id2).toBeTypeOf('string')
    expect(id1).match(/^[0-9]+$/)
    expect(id2).match(/^[0-9]+$/)
    expect(id1).not.toBe(id2)
  })
  it('readableSize', () => {
    expect(readableSize(1024)).toBe('1.00 KB')
    expect(readableSize(1024 * 1024)).toBe('1.00 MB')
    expect(readableSize(1024 * 1024 + 1024)).toBe('1.01 MB')
    expect(readableSize(1024 * 1024 * 1024)).toBe('1.00 GB')
  })
})

describe('conversation', () => {
  it('init', () => {
    const conversation = createConversation('1')
    expect(conversation.id).toBe('1')
    expect(conversation.title).toBe('新对话')
    expect(conversation.running).toBe(false)
    expect(conversation.conversationContextId).toBeUndefined()
    expect(conversation.content).toBeInstanceOf(Array)
    expect(conversation.content.length).toBe(0)
    expect(conversation.running).toBe(false)
    expect(conversation.createMessage).toBeInstanceOf(Function)
    expect(conversation.startWorkflow).toBeInstanceOf(Function)
    expect(conversation.finishWorkflow).toBeInstanceOf(Function)
    expect(conversation.startNode).toBeInstanceOf(Function)
    expect(conversation.finishNode).toBeInstanceOf(Function)
    expect(conversation.onError).toBeInstanceOf(Function)
    expect(conversation.onMessage).toBeInstanceOf(Function)
  })
  it('createMessage', () => {
    const conversation = createConversation('1')
    conversation.createMessage({ creator: 'User', text: ['你好'] })
    expect(conversation.content.length).toBe(1)
    expect(conversation.content[0]?.status === 'Completed').toBeTruthy()
    expect(conversation.content[0]?.done).toBe(false)
  })
  it('fully http response', () => {
    const conversation = createConversation('1')
    conversation.createMessage({ creator: 'Ai', text: [] })
    conversation.startWorkflow()
    expect(conversation.running).toBe(true)
    conversation.startNode()
    expect(conversation.content[0]?.text[0]).toBe('')
    conversation.onMessage('你好！')
    expect(conversation.content[0]?.text[0]).toBe('你好！')
    conversation.finishNode()
    expect(conversation.content[0]?.text.length).toBe(1)
    conversation.startNode()
    expect(conversation.content[0]?.text[1]).toBe('')
    conversation.onMessage('很高兴见到你！😊')
    expect(conversation.content[0]?.text[1]).toBe('很高兴见到你！😊')
    conversation.finishNode()
    expect(conversation.content[0]?.text.length).toBe(2)
    conversation.finishWorkflow()
    expect(conversation.content[0]?.done).toBeTruthy()
    expect(conversation.running).toBe(false)
  })
})
